use rkyv::{Archive, Deserialize, Serialize};

#[derive(Archive, Serialize, Deserialize, Debug, PartialEq)]
#[rkyv(derive(Debug))]
pub struct HgncRecord {
    pub hgnc_id: String,
    pub symbol: String,
    pub name: String,
    pub locus_group: String,
    pub locus_type: String,
    pub status: String,
    pub location: String,
    pub location_sortable: String,
    pub alias_symbol: String,
    pub alias_name: String,
    pub prev_symbol: String,
    pub prev_name: String,
    pub gene_group: String,
    pub gene_group_id: String,
    pub date_approved_reserved: String,
    pub date_symbol_changed: String,
    pub date_name_changed: String,
    pub date_modified: String,
    pub entrez_id: String,
    pub ensembl_gene_id: String,
    pub vega_id: String,
    pub ucsc_id: String,
    pub ena: String,
    pub refseq_accession: String,
    pub ccds_id: String,
    pub uniprot_ids: String,
    pub pubmed_id: String,
    pub mgd_id: String,
    pub rgd_id: String,
    pub lsdb: String,
    pub cosmic: String,
    pub omim_id: String,
    pub mirbase: String,
    pub homeodb: String,
    pub snornabase: String,
    pub bioparadigms_slc: String,
    pub orphanet: String,
    pub pseudogene_org: String,
    pub horde_id: String,
    pub merops: String,
    pub imgt: String,
    pub iuphar: String,
    pub kznf_gene_catalog: String,
    pub mamit_trnadb: String,
    pub cd: String,
    pub lncrnadb: String,
    pub enzyme_id: String,
    pub intermediate_filament_db: String,
    pub rna_central_id: String,
    pub lncipedia: String,
    pub gtrnadb: String,
    pub agr: String,
    pub mane_select: String,
    pub gencc: String,
}

#[derive(Archive, Serialize, Deserialize, Debug, PartialEq)]
#[rkyv(derive(Debug))]
pub struct HgncCache {
    pub records: Vec<HgncRecord>,
    pub lookup: std::collections::HashMap<String, usize>,
}
